name: Terraform Plan and Apply

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Set up AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region "us-east-1"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          if [ "${{ github.event.pull_request.title }}" == "ECR" ]; then
            terraform plan -target=aws_ecr_repository.lambda_repo
          elif [ "${{ github.event.pull_request.title }}" == "Lambda" ]; then
            terraform plan -target=aws_lambda_function.this
          else
            terraform plan
          fi

      - name: Terraform Apply
        run: |
          if [ "${{ github.event.pull_request.title }}" == "ECR" ]; then
            terraform apply -target=aws_ecr_repository.lambda_repo -auto-approve
          elif [ "${{ github.event.pull_request.title }}" == "Lambda" ]; then
            terraform apply -target=aws_lambda_function.this -auto-approve
          else
            terraform apply -auto-approve
          fi
